name: Build Flutter APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        # We specify the folder directly here
        run: flutter pub get
        working-directory: ./flutter_app 

      - name: Build APK
        # And directly here
        run: flutter build apk --debug
        working-directory: ./flutter_app

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          # Path to the file created inside that folder
          path: flutter_app/build/app/outputs/flutter-apk/app-debug.apk